// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiamondShopSystem.Data.Models;

public partial class SideStone
{
    public int SideStoneId { get; set; }

    public string Name { get; set; }

    public string Descriptoin { get; set; }

    public decimal Price { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}