// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiamondShopSystem.Data.Models;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string Email { get; set; }

    public int Gender { get; set; }

    public string Birthday { get; set; }

    public string Address { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}